name: PencilPlugin
version: 0.0.1_ALPHA
api-version: 1.16
main: com.github.polyrocketmatt.pencil.engine.Pencil
description: A lightweight and powerful next generation terrain editor!
load: POSTWORLD
author: PolyRocketMatt
commands:
  pencil:
    description: The main pencil command!